name: Deletar VDB via API do Delphix

on:
  delete:
    branches:
      - '*'         # matches every branch that doesn't contain a '/'
      - '*/*'       # matches every branch containing a single '/'
      - '**'        # matches every branch
      - '!main'     # excludes main
  workflow_dispatch:

jobs:
  # This workflow contains a job to manage VDB and SelfService container life-cycle
  manage_vdbs:
    environment:
      name: delphix-engine
    runs-on: ubuntu-latest
    container: delphix/dxtoolkit:latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Runs a set of commands using the runners shell
      - name: Set dxtools.conf
        run: |
          mkdir /config
          echo {\"data\":[{\"hostname\" : \"Delphix\",\"ip_address\" : \"3.90.65.42\",\"username\" : \"admin\",\"password\" : \"admin\",\"port\" : \"80\",\"default\" : \"false\",\"encrypted\" : \"false\",\"timeout\" : \"60\"}]} > /config/dxtools.conf
                  
                      
       # Deletando VDB
      - name: Remove VDB
        run: dx_remove_db -d Delphix -name ${{ github.event.ref }} -skip

