name: create VDB

on:
  create:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login_CC
        id: Login_CC
        env: 
          delphix-server: 3.90.84.185
        run: curl -s -X POST -k --data @- http://3.90.84.185/resources/json/delphix/login -b ~/cookies.txt -H "Content-Type:application/json" << EOF {"type":"LoginRequest","username":"admin","password":"admin"} EOF
        
 
