name: create VDB

on:
  create:
    branches: ["*"]

steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v2

    - name: Configuração do Ambiente
      env:
        DELPHIX_USER: ${{ secrets.DELPHIX_USER }}
        DELPHIX_PASSWORD: ${{ secrets.DELPHIX_PASSWORD }}
        DELPHIX_HOST: ${{ secrets.DELPHIX_HOST }}
      run: |
        # Configuração do ambiente
        echo "DELPHIX_USER=${DELPHIX_USER}"
        echo "DELPHIX_PASSWORD=${DELPHIX_PASSWORD}"
        echo "DELPHIX_HOST=${DELPHIX_HOST}"
        
    - name: Execução de Script no Delphix
      run: |
        # Comandos para execução de script no Delphix
        echo "Executando script no Delphix"
