name: Criar VDB via API do Delphix

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Repositório
      uses: actions/checkout@v2

    - name: Configuração do Ambiente
      env:
        DELPHIX_USER: ${{ secrets.DELPHIX_USER }}
        DELPHIX_PASSWORD: ${{ secrets.DELPHIX_PASSWORD }}
        DELPHIX_HOST: ${{ secrets.DELPHIX_HOST }}
      run: |
        # Configuração do ambiente
        echo "DELPHIX_USER=${DELPHIX_USER}"
        echo "DELPHIX_PASSWORD=${DELPHIX_PASSWORD}"
        echo "DELPHIX_HOST=${DELPHIX_HOST}"
        
    - name: Criando Section
      run: |
              curl -s -X POST -k --data @- http://3.90.84.185/resources/json/delphix/session \
                -c ~/cookies.txt -H "Content-Type: application/json" <<EOF
              {
                "type": "APISession",
                "version": {
                    "type": "APIVersion",
                    "major": 1,
                    "minor": 4,
                    "micro": 3
                }
              }
              EOF
              
    - name: Login
      run: |
              curl -s -X POST -k --data @- http://3.90.84.185/resources/json/delphix/login \
                -b ~/cookies.txt -H "Content-Type: application/json" <<EOF
              {
                  "type": "LoginRequest",
                  "username": "admin",
                  "password": "admin"
              }
              EOF
    - name: Criando VDB
      run: dx_provision_vdb -d Delphix -group SQLServer_SOURCE -sourcename DS_AdventureWorksLT2019 -targetname TESTEACTIONS -dbname autotest -environment MSSQLSERVER_2019 -type mssql -envinst MSSQLSERVER  

