name: create VDB

on:
  create:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login_CC
        id: Login_CC
        env: 
          delphix-server: x.x.x.x.x
        run: curl -s -X POST -k --data @- http://$delphix-server/resources/json/delphix/login -b ~/cookies.txt -H "Content-Type:application/json" << EOF {"type":"LoginRequest","username":"admin","password":"admin"}EOF
        
      - name: Create_VDB
        id: Create_VDB
        env: 
          delphix-server: x.x.x.x.x
        run: create VDB
